import '../../../core/game_logic/models/piece.dart';
import 'battle_element.dart';

/// Where the battle's sounds live: a theme per attacking unit type and, per
/// element, a shot and an explosion. Generated by `tools/battle_audio/`.
class BattleSounds {
  const BattleSounds._();

  /// The theme played while [attacker] attacks.
  static String music(PieceType attacker) =>
      'assets/audio/music/${attacker.name}.ogg';

  /// A pistol-like shot flavoured by [element].
  static String shot(BattleElement element) =>
      'assets/audio/sfx/${element.name}_shot.ogg';

  /// [element]'s explosion, with a long echo.
  static String explosion(BattleElement element) =>
      'assets/audio/sfx/${element.name}_explosion.ogg';
}
